// Transform fucntion
namespace transform {
  interface Functions {
    // open transfrom dialog
    static void openDialog(DOMString url);
  };

  interface Events {
    // This event fires when click transform pdf to word form action button
    static void onStartTransform();
  };
};
