// Transform fucntion
namespace transform {
  interface Functions {
    // open transfrom dialog
    static void openFileInCurrentTab();
    // open new file
    static void openFileInNewTab();
    // show file in folder
    static void showFileInFloder(DOMString filename);
  };

  interface Events {
    // This event fires when click transform pdf to word form action button
    static void onStartTransform();
  };
};
