// Transform fucntion
namespace transform {
  interface Functions {
    // open transfrom dialog
    static void openDialog(DOMString url);
    // open new file
    static void openFile();
    // show file in folder
    static void showFileInFloder(DOMString filename);
  };

  interface Events {
    // This event fires when click transform pdf to word form action button
    static void onStartTransform();
  };
};
